
// =======================================================
var idExpr = charIDToTypeID( "Expr" );
    var desc5 = new ActionDescriptor();
    var idUsng = charIDToTypeID( "Usng" );
        var desc6 = new ActionDescriptor();
        var idOp = charIDToTypeID( "Op  " );
        var idSWOp = charIDToTypeID( "SWOp" );
        var idOpSa = charIDToTypeID( "OpSa" );
        desc6.putEnumerated( idOp, idSWOp, idOpSa );
        var idDIDr = charIDToTypeID( "DIDr" );
        desc6.putBoolean( idDIDr, true );
        var idIn = charIDToTypeID( "In  " );
        desc6.putPath( idIn, new File( "C:\\Users\\Alena\\Desktop" ) );
        var idovFN = charIDToTypeID( "ovFN" );
        desc6.putString( idovFN, """Circle_10.gif""" );
        var idFmt = charIDToTypeID( "Fmt " );
        var idIRFm = charIDToTypeID( "IRFm" );
        var idGIFf = charIDToTypeID( "GIFf" );
        desc6.putEnumerated( idFmt, idIRFm, idGIFf );
        var idIntr = charIDToTypeID( "Intr" );
        desc6.putBoolean( idIntr, false );
        var idRedA = charIDToTypeID( "RedA" );
        var idIRRd = charIDToTypeID( "IRRd" );
        var idSltv = charIDToTypeID( "Sltv" );
        desc6.putEnumerated( idRedA, idIRRd, idSltv );
        var idRChT = charIDToTypeID( "RChT" );
        desc6.putBoolean( idRChT, false );
        var idRChV = charIDToTypeID( "RChV" );
        desc6.putBoolean( idRChV, false );
        var idAuRd = charIDToTypeID( "AuRd" );
        desc6.putBoolean( idAuRd, false );
        var idNCol = charIDToTypeID( "NCol" );
        desc6.putInteger( idNCol, 128 );
        var idDthr = charIDToTypeID( "Dthr" );
        var idIRDt = charIDToTypeID( "IRDt" );
        var idDfsn = charIDToTypeID( "Dfsn" );
        desc6.putEnumerated( idDthr, idIRDt, idDfsn );
        var idDthA = charIDToTypeID( "DthA" );
        desc6.putInteger( idDthA, 88 );
        var idDChS = charIDToTypeID( "DChS" );
        desc6.putInteger( idDChS, 0 );
        var idDCUI = charIDToTypeID( "DCUI" );
        desc6.putInteger( idDCUI, 0 );
        var idDChT = charIDToTypeID( "DChT" );
        desc6.putBoolean( idDChT, false );
        var idDChV = charIDToTypeID( "DChV" );
        desc6.putBoolean( idDChV, false );
        var idWebS = charIDToTypeID( "WebS" );
        desc6.putInteger( idWebS, 0 );
        var idTDth = charIDToTypeID( "TDth" );
        var idIRDt = charIDToTypeID( "IRDt" );
        var idNone = charIDToTypeID( "None" );
        desc6.putEnumerated( idTDth, idIRDt, idNone );
        var idTDtA = charIDToTypeID( "TDtA" );
        desc6.putInteger( idTDtA, 100 );
        var idLoss = charIDToTypeID( "Loss" );
        desc6.putInteger( idLoss, 0 );
        var idLChS = charIDToTypeID( "LChS" );
        desc6.putInteger( idLChS, 0 );
        var idLCUI = charIDToTypeID( "LCUI" );
        desc6.putInteger( idLCUI, 100 );
        var idLChT = charIDToTypeID( "LChT" );
        desc6.putBoolean( idLChT, false );
        var idLChV = charIDToTypeID( "LChV" );
        desc6.putBoolean( idLChV, false );
        var idTrns = charIDToTypeID( "Trns" );
        desc6.putBoolean( idTrns, true );
        var idMtt = charIDToTypeID( "Mtt " );
        desc6.putBoolean( idMtt, true );
        var idMttR = charIDToTypeID( "MttR" );
        desc6.putInteger( idMttR, 255 );
        var idMttG = charIDToTypeID( "MttG" );
        desc6.putInteger( idMttG, 255 );
        var idMttB = charIDToTypeID( "MttB" );
        desc6.putInteger( idMttB, 255 );
        var idSHTM = charIDToTypeID( "SHTM" );
        desc6.putBoolean( idSHTM, false );
        var idSImg = charIDToTypeID( "SImg" );
        desc6.putBoolean( idSImg, true );
        var idSWsl = charIDToTypeID( "SWsl" );
        var idSTsl = charIDToTypeID( "STsl" );
        var idSLAl = charIDToTypeID( "SLAl" );
        desc6.putEnumerated( idSWsl, idSTsl, idSLAl );
        var idSWch = charIDToTypeID( "SWch" );
        var idSTch = charIDToTypeID( "STch" );
        var idCHsR = charIDToTypeID( "CHsR" );
        desc6.putEnumerated( idSWch, idSTch, idCHsR );
        var idSWmd = charIDToTypeID( "SWmd" );
        var idSTmd = charIDToTypeID( "STmd" );
        var idMDCC = charIDToTypeID( "MDCC" );
        desc6.putEnumerated( idSWmd, idSTmd, idMDCC );
        var idohXH = charIDToTypeID( "ohXH" );
        desc6.putBoolean( idohXH, false );
        var idohIC = charIDToTypeID( "ohIC" );
        desc6.putBoolean( idohIC, true );
        var idohAA = charIDToTypeID( "ohAA" );
        desc6.putBoolean( idohAA, true );
        var idohQA = charIDToTypeID( "ohQA" );
        desc6.putBoolean( idohQA, true );
        var idohCA = charIDToTypeID( "ohCA" );
        desc6.putBoolean( idohCA, false );
        var idohIZ = charIDToTypeID( "ohIZ" );
        desc6.putBoolean( idohIZ, true );
        var idohTC = charIDToTypeID( "ohTC" );
        var idSToc = charIDToTypeID( "SToc" );
        var idOCzerothree = charIDToTypeID( "OC03" );
        desc6.putEnumerated( idohTC, idSToc, idOCzerothree );
        var idohAC = charIDToTypeID( "ohAC" );
        var idSToc = charIDToTypeID( "SToc" );
        var idOCzerothree = charIDToTypeID( "OC03" );
        desc6.putEnumerated( idohAC, idSToc, idOCzerothree );
        var idohIn = charIDToTypeID( "ohIn" );
        desc6.putInteger( idohIn, -1 );
        var idohLE = charIDToTypeID( "ohLE" );
        var idSTle = charIDToTypeID( "STle" );
        var idLEzerothree = charIDToTypeID( "LE03" );
        desc6.putEnumerated( idohLE, idSTle, idLEzerothree );
        var idohEn = charIDToTypeID( "ohEn" );
        var idSTen = charIDToTypeID( "STen" );
        var idENzerozero = charIDToTypeID( "EN00" );
        desc6.putEnumerated( idohEn, idSTen, idENzerozero );
        var idolCS = charIDToTypeID( "olCS" );
        desc6.putBoolean( idolCS, false );
        var idolEC = charIDToTypeID( "olEC" );
        var idSTst = charIDToTypeID( "STst" );
        var idSTzerozero = charIDToTypeID( "ST00" );
        desc6.putEnumerated( idolEC, idSTst, idSTzerozero );
        var idolWH = charIDToTypeID( "olWH" );
        var idSTwh = charIDToTypeID( "STwh" );
        var idWHzeroone = charIDToTypeID( "WH01" );
        desc6.putEnumerated( idolWH, idSTwh, idWHzeroone );
        var idolSV = charIDToTypeID( "olSV" );
        var idSTsp = charIDToTypeID( "STsp" );
        var idSPzerofour = charIDToTypeID( "SP04" );
        desc6.putEnumerated( idolSV, idSTsp, idSPzerofour );
        var idolSH = charIDToTypeID( "olSH" );
        var idSTsp = charIDToTypeID( "STsp" );
        var idSPzerofour = charIDToTypeID( "SP04" );
        desc6.putEnumerated( idolSH, idSTsp, idSPzerofour );
        var idolNC = charIDToTypeID( "olNC" );
            var list1 = new ActionList();
                var desc7 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerozero = charIDToTypeID( "NC00" );
                desc7.putEnumerated( idncTp, idSTnc, idNCzerozero );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc7 );
                var desc8 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNConenine = charIDToTypeID( "NC19" );
                desc8.putEnumerated( idncTp, idSTnc, idNConenine );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc8 );
                var desc9 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwoeight = charIDToTypeID( "NC28" );
                desc9.putEnumerated( idncTp, idSTnc, idNCtwoeight );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc9 );
                var desc10 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc10.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc10 );
                var desc11 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc11.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc11 );
                var desc12 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc12.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list1.putObject( idSCnc, desc12 );
        desc6.putList( idolNC, list1 );
        var idobIA = charIDToTypeID( "obIA" );
        desc6.putBoolean( idobIA, false );
        var idobIP = charIDToTypeID( "obIP" );
        desc6.putString( idobIP, """""" );
        var idobCS = charIDToTypeID( "obCS" );
        var idSTcs = charIDToTypeID( "STcs" );
        var idCSzeroone = charIDToTypeID( "CS01" );
        desc6.putEnumerated( idobCS, idSTcs, idCSzeroone );
        var idovNC = charIDToTypeID( "ovNC" );
            var list2 = new ActionList();
                var desc13 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzeroone = charIDToTypeID( "NC01" );
                desc13.putEnumerated( idncTp, idSTnc, idNCzeroone );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc13 );
                var desc14 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwozero = charIDToTypeID( "NC20" );
                desc14.putEnumerated( idncTp, idSTnc, idNCtwozero );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc14 );
                var desc15 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerotwo = charIDToTypeID( "NC02" );
                desc15.putEnumerated( idncTp, idSTnc, idNCzerotwo );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc15 );
                var desc16 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNConenine = charIDToTypeID( "NC19" );
                desc16.putEnumerated( idncTp, idSTnc, idNConenine );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc16 );
                var desc17 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerosix = charIDToTypeID( "NC06" );
                desc17.putEnumerated( idncTp, idSTnc, idNCzerosix );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc17 );
                var desc18 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc18.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc18 );
                var desc19 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc19.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc19 );
                var desc20 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc20.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc20 );
                var desc21 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwotwo = charIDToTypeID( "NC22" );
                desc21.putEnumerated( idncTp, idSTnc, idNCtwotwo );
            var idSCnc = charIDToTypeID( "SCnc" );
            list2.putObject( idSCnc, desc21 );
        desc6.putList( idovNC, list2 );
        var idovCM = charIDToTypeID( "ovCM" );
        desc6.putBoolean( idovCM, false );
        var idovCW = charIDToTypeID( "ovCW" );
        desc6.putBoolean( idovCW, true );
        var idovCU = charIDToTypeID( "ovCU" );
        desc6.putBoolean( idovCU, true );
        var idovSF = charIDToTypeID( "ovSF" );
        desc6.putBoolean( idovSF, true );
        var idovCB = charIDToTypeID( "ovCB" );
        desc6.putBoolean( idovCB, true );
        var idovSN = charIDToTypeID( "ovSN" );
        desc6.putString( idovSN, """images""" );
    var idSaveForWeb = stringIDToTypeID( "SaveForWeb" );
    desc5.putObject( idUsng, idSaveForWeb, desc6 );
executeAction( idExpr, desc5, DialogModes.NO );